name: Deploy to Vercel

on:
  push:
    branches:
      - main  # ya jo bhi branch tum deploy karna chahte ho

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} \
            --org-id ${{ secrets.VERCEL_ORG_ID }} \
            --project-id ${{ secrets.VERCEL_PROJECT_ID }}
